import { cp, mkdir } from 'node:fs/promises';

await mkdir('public', { recursive: true });
await cp('output/blender/assets', 'public/assets', { recursive: true });
await cp('node_modules/three/examples/jsm/libs/draco/gltf', 'public/draco', { recursive: true });
await mkdir('public/images', { recursive: true });
await cp('output/blender/finished/exterior.png', 'public/images/exterior.png');
await cp('output/blender/finished/interior.png', 'public/images/interior.png');
await cp('output/blender/textures/gltf/spruce-color.png', 'public/images/wood.png');

// Sauna configurator: catalog/presets data and the pre-built preset renders
// and GLBs, all generated by the blender/ pipeline (blender/build_presets.py).
await mkdir('public/data', { recursive: true });
await cp('blender/catalog.json', 'public/data/catalog.json');
await cp('blender/presets.json', 'public/data/presets.json');
await mkdir('public/images/presets', { recursive: true });
await mkdir('public/models/presets', { recursive: true });
const presetImages = [
  ['output/blender/configurator/presets/espoo-compact-exterior.png', 'public/images/presets/espoo-compact.png'],
  ['output/blender/configurator/presets/fichte-fenster-l-exterior.png', 'public/images/presets/fichte-fenster-l.png'],
  ['output/blender/configurator/presets/designer-espe-schiefer-exterior.png', 'public/images/presets/designer-espe-schiefer.png'],
];
for (const [from, to] of presetImages) {
  try { await cp(from, to); } catch { /* renders are optional; run blender/build_presets.py --render to regenerate */ }
}
try { await cp('output/blender/configurator/presets', 'public/models/presets', { recursive: true, filter: src => src.endsWith('.glb') || !src.includes('.') }); }
catch { /* GLBs are optional; run blender/build_presets.py to regenerate */ }

console.log('Blender assets, sauna catalog data and configurator presets are ready.');
